[env:esp32]
platform = espressif32@6.4.0
framework = espidf
board = esp32dev
monitor_speed = 115200
build_flags = -DIWDT_TEST_MODE=0
platform_packages =
    platformio/framework-espidf@~3.40407.0
    espressif/toolchain-xtensa-esp32@8.4.0+2021r2-patch5

[platformio]
platforms_dir = C:/SourceCode/LasecSimul/.piohome/platforms
packages_dir = C:/SourceCode/LasecSimul/.piohome/packages
cache_dir = C:/SourceCode/LasecSimul/.piohome/cache
