// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler
// Do not edit this file manually.

#include "hello.generated.hpp"

namespace strucpp {

// Library: iec-standard-fb
TON::TON() {
    // Initialize variables
}

void TON::operator()() {
    CURRENT_TIME = TIME();
    if (((((STATE == 0)) & (NOT(PREV_IN))) & (IN))) {
        STATE = 1;
        Q = false;
        START_TIME = CURRENT_TIME;
    } else {
        if ((NOT(IN))) {
            ET = 0LL;
            Q = false;
            STATE = 0;
        } else if ((STATE == 1)) {
            if (((START_TIME + PT) <= CURRENT_TIME)) {
                STATE = 2;
                Q = true;
                ET = PT;
            } else {
                ET = CURRENT_TIME - START_TIME;
            }
        }
    }
    PREV_IN = IN;
}


// =============================================================================
// Located Variables Descriptor Array
// =============================================================================

LocatedVar locatedVars[1] = {
    { LocatedArea::Input, LocatedSize::Bit, 0, 0, {0, 0, 0}, nullptr }  // placeholder; locatedVarsCount is 0
};

#ifdef STRUCPP_THREADED
// Canonical storage pointers of the located CONFIGURATION VAR_GLOBALs.
// Populated in the configuration constructor (like locatedVars[] above).
void *locatedGlobals[1] = {
    nullptr  // placeholder; locatedGlobalsCount is 0
};

// C linkage: a host runtime is built once and loads many .so files, so it
// cannot reach namespaced C++ symbols by mangled name portably.
extern "C" void *const *strucpp_get_located_globals(void) { return locatedGlobals; }
extern "C" uint32_t strucpp_get_located_global_count(void) { return locatedGlobalsCount; }
#endif  // STRUCPP_THREADED

}  // namespace strucpp
// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler
// Do not edit this file manually.

#include "hello.generated.hpp"

namespace strucpp {

Program_HELLO::Program_HELLO()
    : DI0(false), DO0(false)
{
}

void Program_HELLO::run() {
#line 15 "hello.st"
    TIMER0.IN = DI0;
    TIMER0.PT = 500000000LL;
    TIMER0();
    TIMER0.ENO = true;
#line 16 "hello.st"
    DO0 = TIMER0.Q;
#line 18 "hello.st"
}

}  // namespace strucpp