import fs from 'node:fs';
const [,,path,out='r3d0-tails.csv',etlStart='0',etlEnd='18446744073709551615']=process.argv;
if(!path){console.error('usage: node reconcile-r3d0.mjs core.trace [csv] [etlStart] [etlEnd]');process.exit(2)}
const b=fs.readFileSync(path), hs=64, size=b.readUInt32LE(12), n=Math.min(Number(b.readBigUInt64LE(40)),Math.floor((b.length-hs)/size));
const m=new Map(); const keyOf=r=>[r.s,r.r,r.g,r.t].join('/');
for(let i=0;i<n;i++){const o=hs+i*size, et=b.readUInt16LE(o+80), r={s:b.readBigUInt64LE(o+8),r:b.readBigUInt64LE(o+16),g:b.readBigUInt64LE(o+24),t:b.readBigUInt64LE(o+32),q:b.readBigUInt64LE(o+64),tid:b.readUInt32LE(o+76),v:b.readBigUInt64LE(o+56),d0:size>=128?b.readBigUInt64LE(o+120):0n,r3:size>=144?b.readBigUInt64LE(o+136):0n}; if(et!==2&&et!==22)continue; const k=keyOf(r),x=m.get(k)||{...r}; if(et===2){x.t3=r.q;x.tid=r.tid;x.v3=r.v} else {x.d0=r.d0;x.r3=r.r3;x.v4=r.v} m.set(k,x); }
const all=[...m.values()], valid=all.filter(x=>x.r3&&x.d0&&x.d0>=x.r3), bad=all.filter(x=>x.r3&&x.d0&&x.d0<x.r3), missingR3=all.filter(x=>!x.r3),missingD0=all.filter(x=>!x.d0), uniq=new Set(all.map(keyOf));
const tails=valid.filter(x=>x.d0-x.r3>=100n).sort((a,b)=>a.t<b.t?-1:1);
fs.writeFileSync(out,['sessionExecutionId,runtimeInstanceId,launchGeneration,transactionSequence,threadId,R3_raw_qpc,D0_raw_qpc,gap_ticks,gap_us',...tails.map(x=>[x.s,x.r,x.g,x.t,x.tid,x.r3,x.d0,x.d0-x.r3,Number(x.d0-x.r3)/10].join(','))].join('\n')+'\n');
const vals=valid.map(x=>Number(x.d0-x.r3)/10).sort((a,b)=>a-b), pct=p=>vals.length?vals[Math.floor(p*(vals.length-1))]:0; const thresholds=[1,2,5,10,20,50,100].map(u=>`${u}us=${valid.filter(x=>x.d0-x.r3>=BigInt(u*10)).length}`).join(' ');
console.log(JSON.stringify({core:path,recordSize:size,recordsParsed:n,transactionIdentities:all.length,uniqueIdentities:uniq.size,duplicateIdentities:all.length-uniq.size,validR3D0Pairs:valid.length,missingR3:missingR3.length,missingD0:missingD0.length,invalidOrdering:bad.length,thresholds,min:pct(0),median:pct(.5),p90:pct(.9),p95:pct(.95),p99:pct(.99),max:pct(1),tails10us:tails.length,etlWindow:{start:etlStart,end:etlEnd},inside:valid.filter(x=>x.r3>=BigInt(etlStart)&&x.d0<=BigInt(etlEnd)).length,outside:valid.filter(x=>x.r3<BigInt(etlStart)||x.d0>BigInt(etlEnd)).length,tidCounts:Object.fromEntries([...new Set(valid.map(x=>x.tid))].map(t=>[t,valid.filter(x=>x.tid===t).length]))},null,2));
