import fs from 'node:fs';
const path=process.argv[2]||'.codex-validation/xperf-core.trace'; const b=fs.readFileSync(path),sz=b.readUInt32LE(12),n=Number(b.readBigUInt64LE(40)); const m=new Map();
for(let i=0;i<Math.min(n,(b.length-64)/sz);i++){let o=64+i*sz,e=b.readUInt16LE(o+80),k=b.readBigUInt64LE(o+32);if(e===2)m.set(k,{k,s:b.readBigUInt64LE(o+8),r:b.readBigUInt64LE(o+16),g:b.readBigUInt64LE(o+24),t:k,tid:b.readUInt32LE(o+76),t3:b.readBigUInt64LE(o+64),v3:b.readBigUInt64LE(o+56)});else if(e===22&&m.has(k)){let x=m.get(k);x.r3=b.readBigUInt64LE(o+136);x.d0=b.readBigUInt64LE(o+120);x.t4=b.readBigUInt64LE(o+64);x.v4=b.readBigUInt64LE(o+56);}}
const a=[...m.values()].filter(x=>x.r3&&x.d0&&x.d0>=x.r3&&x.v4>=x.v3), tails=a.filter(x=>x.d0-x.r3>=100n), vd=x=>Number(x.v4-x.v3), host=x=>Number(x.d0-x.r3)/10, pct=(v,p)=>{v=[...v].sort((a,b)=>a-b);return v[Math.floor(p*(v.length-1))]||0};
const union=xs=>{xs=xs.sort((a,b)=>a[0]<b[0]?-1:1);let z=0,s=null,e=null;for(const x of xs){if(s===null){s=x[0];e=x[1]}else if(x[0]>e){z+=Number(e-s);s=x[0];e=x[1]}else if(x[1]>e)e=x[1]}return s===null?0:z+Number(e-s)};
console.log('authoritative',a.length,'tails',tails.length,'extra2262',2262-a.length); console.log('virtual thresholds',...[1,10,100,1000].map(u=>`${u}us=${tails.filter(x=>vd(x)>=u*1000).length}`).join(' '));
for(const x of tails.filter(x=>vd(x)>=100000)) console.log('OUTLIER',x.s,x.r,x.g,x.t,x.tid,'v3',x.v3.toString(),'v4',x.v4.toString(),'vd_ns',vd(x),'r3',x.r3.toString(),'d0',x.d0.toString(),'host_us',host(x));
for(const [name,pred] of [['A',x=>vd(x)<10000],['B',x=>vd(x)>=10000&&vd(x)<100000],['C',x=>vd(x)>=100000&&vd(x)<1000000],['D',x=>vd(x)>=1000000]]){let q=tails.filter(pred);console.log('GROUP',name,q.length,'hostMed',pct(q.map(host),.5),'offCpuUnavailableUntilETWIntervals');}
const wall=a.reduce((z,x)=>z+Number(x.d0-x.r3),0)/10, uni=union(a.map(x=>[x.r3,x.d0])); console.log('summedR3D0Us',wall,'unionR3D0Us',uni/10,'analyzedWindowUs',(Number(a.reduce((z,x)=>z<x.r3?z:x.r3,a[0].r3)),Number(a.reduce((z,x)=>z>x.d0?z:x.d0,a[0].d0))-Number(a.reduce((z,x)=>z<x.r3?z:x.r3,a[0].r3)))/10); console.log('tid tails',Object.fromEntries([...new Set(tails.map(x=>x.tid))].map(t=>[t,tails.filter(x=>x.tid===t).length])));
